### ISSUE TITLE
`drop_remainder` in `DataPipeline.shard`

### ISSUE THREAD

**Issue by chaoweihuang** [facebookresearch/fairseq2#147]
**Is your feature request related to a problem? Please describe:**
I'm using fairseq2 data pipeline for distributed inference. The current behavior of `DataPipeline.shard` is to discard remaining samples since it only returns the sample after iterating through `world_size` samples.

**Describe the solution you would like:**
An option `drop_remainder` which is similar to the one in `DataPipeline.bucket`.

**Describe the alternatives you have considered:**
I was thinking about maybe implement a custom sharding pipeline function in python but couldn't find a way to do that.

**Comment by cbalioglu** [comment]
Please see #451
