### ISSUE TITLE
pytorch version of WaveformToFbankConverter

### ISSUE THREAD

**Issue by KeepSilentNow** [facebookresearch/fairseq2#298]
I have a question and would greatly appreciate your help! For the audio feature processor [WaveformToFbankConverter](https://github.com/facebookresearch/fairseq2/blob/f2be5c0196ac9eb566a1d2bc5ef3544f59220a83/src/fairseq2/data/audio.py#L32C1-L32C36), is there a PyTorch implementation available for understanding? Thank you very much!

**Comment by cbalioglu** [comment]
Hey @KeepSilentNow, not sure if you deliberately closed this PR, but we use a statically build version of Kaldi Fbank converter for `WaveformToFbankConverter`. Although it is not %100 same code, you can check out the torchaudio version (which is based on Python + PyTorch) [here](https://github.com/pytorch/audio/blob/02586da797dbfa201721d2080e2171805202f72c/src/torchaudio/compliance/kaldi.py#L514).

**Comment by KeepSilentNow** [comment]
Yes, I've solved the problem on my own and closed the PR, but thank you very much for your reply anyway!
