### ISSUE TITLE
w2v-bert weights

### ISSUE THREAD

**Issue by aabzaliev** [facebookresearch/fairseq2#31]
Hi fairseq2 team! 

README mentions that w2v-bert is avaliable as a pre-trained model, but I cannot find the link to download the weights anywhere - only the classes. I can see the links for S2T under assets/cards/*.yaml, but not for w2v-bert. Are you planning to release the weights?

Also, SeamlessM4T mentions w2v-bert 2.0 - are there any plans to open-source it as well? 

Thank you for your excellent work, much appreciated!

Best,
Artem

**Comment by cbalioglu** [comment]
Hey @aabzaliev,

> README mentions that w2v-bert is avaliable as a pre-trained model, but I cannot find the link to download the weights anywhere - only the classes.

Actually the speech encoder part of the SeamlessM4T model (except the M-Adaptor layers) is the w2v-BERT pretrained model. So it requires a bit manual work, but you can extract those weights from the released checkpoint.

> I can see the links for S2T under assets/cards/*.yaml, but not for w2v-bert. Are you planning to release the weights?

I am not aware of a specific plan to release them as standalone weights. I think you might get a better answer in seamless_communication repo though.

> Thank you for your excellent work, much appreciated!

Thank you very much!

**Comment by cbalioglu** [comment]
Closing this issue as answered. As I mentioned, please follow up in the seamless_commnucation repo for further questions about the release of pretrained weights.
