### ISSUE TITLE
DatapipelineBuilder.map should not implicitly convert python object

### ISSUE THREAD

**Issue by artemru** [facebookresearch/fairseq2#375]
DataPipelineBuilder tries to convert python data internally (basically all iterables) which may not work for may python objects.
Below I show the some example (that are currently of importance for parquet dataloader)
```python
import pyarrow as pa
import pandas as pd
from fairseq2.data import read_sequence

list_of_objects = [pa.Table.from_pydict({"a": list(range(i + 1))}) for i in range(3)]
read_sequence(list_of_objects) # -> IndexError: index out of bounds

list_of_objects = [pd.DataFrame({"a": list(range(i + 1))}) for i in range(3)]
read_sequence(list_of_objects) # -> KeyError: 0
```
which is unexpected.
**Describe the solution you would like:**
I want to be able to use any python object inside a fairseq2 datapipeline, 
or at least to be able to turn off the implicit conversion locally.

**Describe the alternatives you have considered:**
Alternative was already realized in [parquet dataloader](https://github.com/facebookresearch/fairseq2/blob/main/src/fairseq2/data/parquet_tools.py#L230) and consisted in wrapping python object into some non-iterable class.

**Comment by cbalioglu** [comment]
@artemru I just tried to reproduce the problem, but can't really find any issues. So you are passing a list of `pa.Table` instances (or `pd.DataFrame`) to `read_sequences()`, and when you iterate on the returned data pipeline, each returned value is a `pa.Table` or `pd.DataFrame` as expected. The data pipeline builder should only convert concrete `dict` and `list` types to their C++ counterparts. For all other iterables it should preserve the original Python object. If you observe a different behavior, please let me know. Unfortunately in this specific example, I can't see that issue.

**Comment by artemru** [comment]
indeed, it seems to be fixed with new version... maybe something else was wrong in my install. I'm closing it as now !
