### ISSUE TITLE
where is checkpoint directory?

### ISSUE THREAD

**Issue by Viktour19** [facebookresearch/fairseq2#427]
I have a pretty basic question - where does the checkpoint get downloaded to?

```
    config = _conformer_shaw_600m()
    model = create_conformer_shaw_model(config, device=device, dtype=dtype)
    model.eval()
```

**Comment by cbalioglu** [comment]
Hi @Viktour19, by default they are downloaded to `~/.cache/fairseq2/assets` directory, but you can change it with the `FAIRSEQ2_CACHE_DIR` environment variable. Here the relevant code: https://github.com/facebookresearch/fairseq2/blob/main/src/fairseq2/assets/download_manager.py#L127
