### ISSUE TITLE
pip install fairseq2 requires pytorch2 via fairseq2n

### ISSUE THREAD

**Issue by frmccann97** [facebookresearch/fairseq2#43]
I am really struggling to install faiseq2 via a dependency manager as the installation triggers fairseq2n which requires pytorch2. Have tried specifying --extra-index-url https://fair.pkg.atmeta.com/fairseq2/whl/pt1.13.1/cu116 but that still doesn't circumvent pytorch2 requirement

**Comment by cbalioglu** [comment]
Hey @frmccann97, do you mind sharing the output of your pip command?

**Comment by frmccann97** [comment]
Yeah, for a bit more context I am using python 3.8.10 and am constrained to using torch==1.13.1.

The error is basically that the different torch versions can't be resolved. I'm basically trying to avoid upgrading to pytorch 2.0 if possible as that would involve paying down a lot of tech debt.

**Comment by frmccann97** [comment]
Working on getting the exact output

**Comment by frmccann97** [comment]
```
`ERROR: Cannot install -r /home/francis/test-reqs2.txt (line 2), fairseq2 and torch==1.13.01 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==1.13.01
    fairseq2 0.1.0 depends on torch>=1.12.1
    fairseq2n 0.1.0 depends on torch==2.0.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`
```

**Comment by cbalioglu** [comment]
@frmccann97 are you sure that fairseq2 0.1.0 is not already installed in your virtual environment? It is surprising to see that pip install still resolves to 0.1.0. Have you tried running the installation in a complete new virtual environment?

**Comment by frmccann97** [comment]
`ERROR: fairseq2n 0.1.1 has requirement torch==2.0.1, but you'll have torch 1.13.1 which is incompatible.
Installing collected packages: wheel, nvidia-cublas-cu11, nvidia-cudnn-cu11, nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, typing-extensions, torch, torcheval, colorama, portalocker, tabulate, regex, lxml, numpy, sacrebleu, pyyaml, rapidfuzz, click, jiwer, packaging, tqdm, tbb, fairseq2n, overrides, fairseq2
Successfully installed click-8.1.7 colorama-0.4.6 fairseq2-0.1.1 fairseq2n-0.1.1 jiwer-3.0.3 lxml-4.9.3 numpy-1.24.4 nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 overrides-7.4.0 packaging-23.1 portalocker-2.7.0 pyyaml-6.0.1 rapidfuzz-3.3.0 regex-2023.8.8 sacrebleu-2.3.1 tabulate-0.9.0 tbb-2021.9.0 torch-1.13.1 torcheval-0.0.7 tqdm-4.66.1 typing-extensions-4.7.1 wheel-0.41.2`

Same error but gets latest version

**Comment by cbalioglu** [comment]
@frmccann97 are you installing fairseq2 with just `pip install fairseq2` which depends on the latest PyTorch version? Note that for older PyTorch versions you have to use the `--extra-index-url` option as described [here](https://github.com/facebookresearch/fairseq2#variants).

**Comment by frmccann97** [comment]
fairseq2  --extra-index-url https://fair.pkg.atmeta.com/fairseq2/whl/pt1.13.1/cu116
Thats the exact requirement im attempting to install

**Comment by droganov** [comment]
Hi, same issue for me

```
Mac OS 13.1 (22C65)
2,6 GHz 6-Core Intel Core i7

python --version
python 3.10.7

pip --version
pip 22.2.2

which pip
/Users/.../seamless_m4t/env/bin/pip
```

both `pip install fairseq2` and `pip install fairseq2  --extra-index-url https://fair.pkg.atmeta.com/fairseq2/whl/pt2.0.1/cu118 ` result in:

```
ERROR: Cannot install fairseq2==0.1.0 and fairseq2==0.1.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    fairseq2 0.1.1 depends on fairseq2n==0.1.1
    fairseq2 0.1.0 depends on fairseq2n==0.1.0
```

**Comment by droganov** [comment]
https://nextjs.org/docs/app/building-your-application/rendering/client-components#using-client-components-in-nextjs

**Comment by cbalioglu** [comment]
@frmccann97 unfortunately not. Can you try to manually download the wheel file of fairseq2n and install it that way?

https://fair.pkg.atmeta.com/fairseq2/whl/pt1.13.1/cu116/fairseq2n/fairseq2n-0.1.1+cu116-cp38-cp38-manylinux2014_x86_64.whl

**Comment by cbalioglu** [comment]
@frmccann97 @droganov please let me know if you still experience this issue with v0.2. Feel free to re-open this or create a new issue.

**Comment by skywindy** [comment]
my computer only suport cuda113 , so i only can install torch<=1.12.1 ,but fairseq2n depend on torch>=2.0.0. so how can i fix this problem?
