### ISSUE TITLE
license issue for w2v-bert

### ISSUE THREAD

**Issue by feng-yufei** [facebookresearch/fairseq2#48]
Hi fairseq2 team, 
Thank you for open-sourcing w2v-bert, I wonder:

What will be the license to the w2v-bert weights?  it is released with seamless-m4t, which is cc-by-nc, but fairseq2 is MIT licensed. I spotted in previous issues that this repo does not plan to release standalone w2v-bert, so If I extract the weights from m4t, which license should I use?

**Comment by cbalioglu** [comment]
Hi, MIT license only applies to the source code of the fairseq2 project (which happens to also include an implementation of the w2v-BERT model). However all pretrained weights are subject to the license of the owning project; in this case seamless_communication. In summary, the weights are licensed under cc-by-nc.

**Comment by feng-yufei** [comment]
thanks for the quick reply!

**Comment by cbalioglu** [comment]
You are welcome!
