### ISSUE TITLE
SentencePieceDecoder to have a helper function which converts token indices to a list of string tokens and not just complete sentences

### ISSUE THREAD

**Issue by kauterry** [facebookresearch/fairseq2#56]
**Is your feature request related to a problem? Please describe:**
Currently we have to loop through each batch, and each token in the batch, and call the SPM model's `index_to_token` method which is very efficient.

The `SentencePieceDecoder` converts token indices to complete sentences directly. (https://github.com/facebookresearch/fairseq2/blob/main/src/fairseq2/data/text/sentencepiece.py#L85-L91)
```
       @finaloverride
        def __call__(self, token_indices: Tensor) -> List[StringLike]:
            ...
```

I need a method which takes in token indices, and just converts it to a list of string tokens. Currently we are having to call `index_to_token` on each token index.

**Describe the solution you would like:**
Instead of joining all the string tokens into a single sentence, it would be nice to have an option to just return the list of string tokens as well, without the concatenation into a single string sentence.
```
       @finaloverride
        def get_tokens(self, token_indices: Tensor) -> List[List[StringLike]]:
            ...
```
**Describe the alternatives you have considered:**
A clear and concise description of any alternative solutions or features you have considered.

**Additional Context:**
We want to deprecate this method: 

https://github.com/fairinternal/seamless_communication/blob/main/src/seamless_communication/models/unity/nar_decoder_frontend.py#L134-L145

with the `get_tokens` method built in the `SentencePieceDecoder`.

**Comment by cbalioglu** [comment]
Resolved in #154
