### ISSUE TITLE
AMD compilation error

### ISSUE THREAD

**Issue by taikai-zz** [facebookresearch/fairseq2#583]
>>> import torch
>>> torch.cuda.is_available() 
True
>>> device_name = torch.cuda.get_device_name(0)
>>> print("device_name:", device_name)
device_name: AMD Radeon PRO W6800
>>> print(torch.__version__)
2.1.0+rocm5.6
>>> print(sys.version)
3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
cd fairseq2/native
cmake -GNinja -DCMAKE_HIP_ARCHITECTURES="gfx1030" -DFAIRSEQ2N_USE_HIP=ON -B build

CMake Error at third-party/fmt.cmake:11 (add_subdirectory):
  The source directory

    /data/AI/seamless-m4t-v2-large/fairseq2/native/third-party/fmt

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:193 (fairseq2n_add_fmt)

CMake Error at third-party/fmt.cmake:13 (target_compile_features):
  Cannot specify compile features for target "fmt" which is not built by this
  project.
Call Stack (most recent call first):
  CMakeLists.txt:193 (fairseq2n_add_fmt)

CMake Error at third-party/fmt.cmake:15 (set_target_properties):
  set_target_properties Can not find target to add properties to: fmt
Call Stack (most recent call first):
  CMakeLists.txt:193 (fairseq2n_add_fmt)

CMake Error at third-party/fmt.cmake:24 (target_link_libraries):
  Cannot specify link libraries for target "fmt" which is not built by this
  project.
Call Stack (most recent call first):
  CMakeLists.txt:193 (fairseq2n_add_fmt)

-- Configuring incomplete, errors occurred!

May I ask what the problem is.？

**Comment by cbalioglu** [comment]
@taikai-zz please make sure that all git submodules are initialized: `git submodule update --init --recursive`.

**Comment by cbalioglu** [comment]
closing, but feel free to reopen it if the issue persists.
