### ISSUE TITLE
documentation and training recipes

### ISSUE THREAD

**Issue by zhhao1** [facebookresearch/fairseq2#682]
Thank you so much for the great work. I wonder if there are documentation and training examples for quick use.

**Comment by alvations** [comment]
+1 on the training recipes doc!

Esp. if there's any additional preprocessing steps to convert textfiles to fairseq2 trainable format like in fairseq 1.

**Comment by LPX55** [comment]
@alvations @zhhao1

Unless I'm utterly lost or have missed something completely, I'm pretty sure [the docs](https://facebookresearch.github.io/fairseq2/stable) that are linked from the repo is not up-to-date. Your best bet is probably to [build them locally](https://github.com/facebookresearch/fairseq2/tree/main/doc) -- you'll find that there are references and tutorials that are much more helpful.

**Comment by zyaoj** [comment]
@LPX55

thanks for the mention! Documentation is OTW and you can find the latest build with our [nightly documentation](https://facebookresearch.github.io/fairseq2/nightly/index.html).


@zhhao1 @alvations

Please take a look at [this tutorial](https://facebookresearch.github.io/fairseq2/nightly/tutorials/end_to_end_fine_tuning.html) and let us know if it is helpful.

**Comment by math-nao** [comment]
Hello,

I did follow installation instructions from [nightly documentation](https://facebookresearch.github.io/fairseq2/nightly/index.html) but it doesn't seem to install fairseq2 command lines, it installs fairseq2 python package without command lines.

Python bin folder contains files such as `torchrun`, `tabulate`, `sacrebleu` etc... (fairseq2 dependencies) but no `fairseq2`.

`Successfully installed MarkupSafe-3.0.2 click-8.1.7 colorama-0.4.6 fairseq2-0.2.1 fairseq2n-0.2.1 filelock-3.16.1 fsspec-2024.10.0 jinja2-3.1.4 jiwer-3.0.5 lxml-5.3.0 mpmath-1.3.0 networkx-3.4.2 numpy-1.26.4 overrides-7.7.0 packaging-23.2 portalocker-3.0.0 pyyaml-6.0.2 rapidfuzz-3.10.1 regex-2024.11.6 sacrebleu-2.4.3 sympy-1.13.3 tabulate-0.9.0 torch-2.2.2 torcheval-0.0.7 tqdm-4.67.1 typing-extensions-4.12.2`

Is there a step missing in documentation?

Thank you for your help.

**Comment by zyaoj** [comment]
Closing this now. Please let us know if there's any documentation you want to see.
