### ISSUE TITLE
Compile a matmul + reduction op in vector quantizer to avoid excess memory usage.

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/fairseq2#832]
Current memory profile

![Screenshot 2024-10-02 at 5 57 55 PM](https://github.com/user-attachments/assets/1872cfee-b608-4e20-a7d1-0b6738e2e527)

**Comment by kauterry** [comment]
Hey @shagunsodhani! How did you figure out this specific quantizer op was the reason for the memory spikes?

**Comment by shagunsodhani** [comment]
@kauterry sorry for the late reply - I used the profiler traces to map the op with the memory spike.
