### ISSUE TITLE
No matching distribution found for fairseq2n<=0.3.0,>=0.3.0.dev0

### ISSUE THREAD

**Issue by sunrise224** [facebookresearch/fairseq2#855]
I would like to ask how to install version 0.3.0.dev0 of fairseq2n. I was trying to installed fairseq2 0.3.0.dev0 from source, but I couldn't find version 0.3.0.dev0 of fairseq2n on PyPI.

If I install fairseq2 via pip, it will install version 0.2.1, and the command-line tool will be missing
![Uploading 1732251508708.jpg…]()

**Comment by zyaoj** [comment]
@suchenyang2023 

To install fairseq2n nightly (e.g. `torch_version=2.4.0` and `$cuda_version=12.1`):
```
pip install fairseq2n --pre --upgrade\
    --extra-index-url https://fair.pkg.atmeta.com/fairseq2/whl/nightly/pt$torch_version/cu${cuda_version//.}
```

To install fairseq2 (editable):
```
git clone git@github.com:facebookresearch/fairseq2.git
cd fairseq2
pip install --editable .
```

**Comment by suchenyang2023** [comment]
thank you. pip install fairseq2n --pre --upgrade\
    --extra-index-url https://fair.pkg.atmeta.com/fairseq2/whl/nightly/pt$torch_version/cu${cuda_version//.} this solved my problem. I found that the combination of torch_version=2.4.0 and $cuda_version=12.1 only has wheel files available in the nightly build. Additionally, I encountered an issue where the error message states that root_gang.size=1 cannot be evenly divided by the tensor parallel size of 8, even though 8 GPUs have already been detected in the logs. How might this issue be resolved? Thank you very much!

**Comment by zyaoj** [comment]
Have you checked `torch.cuda.device_count()`? In fairseq2, the `ProcessGroupGang` is wrapper of `torch.distributed`. For example:
```
import torch.distributed as dist

# if you are using cuda
dist.init_process_group("cuda")
pg = dist.group.WORLD

# to check the world size -- i.e. root_gang.size
dist.get_world_size(pg)
```

Reference: https://github.com/facebookresearch/fairseq2/blob/main/src/fairseq2/gang.py#L412-L421

**Comment by zyaoj** [comment]
Closing this now since the original issue has been resolved. Please let me know if further assistance is required on this topic.
