### ISSUE TITLE
No wheels available for torch 2.5 (readme is incorrect and has 404 wheel URLs)

### ISSUE THREAD

**Issue by lukasschmit** [facebookresearch/fairseq2#869]
The readme indicates that fairseq2 binaries are available for torch 2.5.1. The exact command in the readme:

pip install fairseq2 --extra-index-url https://fair.pkg.atmeta.com/fairseq2/whl/pt2.5.1/cu124
will just install the pypi fairseq2 as the provided url 404's. The binaries DO exist for the nightly builds, but I also need for fairseq2 0.2.1.

Do this builds actually exist and the readme simply has the wrong URL, or are there no plans for fairseq2 to support newer torch versions and the "variants" / "nightly" sections of the readme have been intermixed erroneously?

**Comment by blair-wdq** [comment]
I would also love these wheels. My team is migrating to torch 2.5.

**Comment by cbalioglu** [comment]
Hey @lukasschmit, yes this is a documentation bug that we should fix. We do not have v0.2.1 available for PyTorch 2.5.1 at the moment. We plan to have a v0.3.0 release soon (release candidate landing today, the final release before end of year). Is there a specific reason you need v0.2.1? Same question to @blair-wdq  :)

**Comment by cbalioglu** [comment]
Fixed the README. Let me know if you have further questions regarding v0.2.1 support. Closing this issue for now.
