### ISSUE TITLE
fairseq2 installation issue: ImportError: cannot import name 'default_asset_store' from 'fairseq2.assets'

### ISSUE THREAD

**Issue by nitishpandey04** [facebookresearch/fairseq2#893]
**Describe the bug:**
`pip install fairseq2` is not working

**Describe how to reproduce:**
Here's a link to kaggle notebook to reproduce the error - [link](https://www.kaggle.com/code/nitishpandey04/sonar-encoders)

**Describe the expected behavior:**
`sonar-space` library uses `fairseq2` library. When sonar-space is calling fairseq2 internally, below error is coming-

ImportError                               Traceback (most recent call last)
Cell In[4], line 1
----> 1 from sonar.inference_pipelines.text import TextToEmbeddingModelPipeline
      2 from sonar.models.blaser.loader import load_blaser_model
      4 # blaser_qe = load_blaser_model("blaser_2_0_qe").eval()
      5 # text_embedder = TextToEmbeddingModelPipeline(encoder="text_sonar_basic_encoder", tokenizer="text_sonar_basic_encoder")
      6 
   (...)
      9 
     10 # print(blaser_qe(src=src_embs, mt=mt_embs).item())  # 4.708

File /opt/conda/lib/python3.10/site-packages/sonar/__init__.py:9
      1 # Copyright (c) Meta Platforms, Inc. and affiliates.
      2 # All rights reserved.
      3 #
      4 # This source code is licensed under the BSD-style license found in the
      5 # LICENSE file in the root directory of this source tree.
      7 """SONAR provides a set of speech and text encoders for multilingual, multimodal semantic embedding."""
----> 9 from fairseq2.assets import default_asset_store
     11 __version__ = "0.3.2"
     14 def setup_fairseq2() -> None:
     15     # Make sure that the default fairseq2 asset store can resolve cards under
     16     # the directory <sonar>/cards.

ImportError: cannot import name 'default_asset_store' from 'fairseq2.assets' (/opt/conda/lib/python3.10/site-packages/fairseq2/assets/__init__.py)

**Environment:**
pytorch - 2.2.2
python - 3.10.14
fairseq2 - 0.2.1
sonar-space - 0.3.2
processor - CPU on kaggle

**Additional Context:**
sonar-space depends on fairseq2 but it doesn't install fairseq2 by itself, we have to install it separately. So, I don't think the issue is with sonar-space. This is a fairseq2 installation issue I believe.

**Comment by cbalioglu** [comment]
Hi @nitishpandey04, sonar-space project uses fairseq2 0.3.0rc1 instead of fairseq2 0.2.1. You can install it using:

```
pip install fairseq2==v0.3.0rc1 --pre --extra-index-url  https://fair.pkg.atmeta.com/fairseq2/whl/rc/pt2.5.1/cpu
```

Make sure to change the PyTorch version and variant accordingly. More details are included in large-concept-model repo's README here: https://github.com/facebookresearch/large_concept_model?tab=readme-ov-file#using-pip
