### ISSUE TITLE
Issue with fairseq2 lm instruction_finetune on version 0.3.0.dev202412020149+g2ab8245.cu121

### ISSUE THREAD

**Issue by sunrise224** [facebookresearch/fairseq2#923]
Running fairseq2 lm instruction_finetune ./sft --config-file ./training_configs/sft_training.yaml on single node 8 h100 80g
and the sft_training.yaml：

dataset: sft_training_data  # asset name from the card 'training_data.yaml'
max_seq_len: 4096
max_num_tokens: 8192
example_shuffle_window: 10000
batch_shuffle_window: 1000
num_prefetch: 4
model: llama3_1_70b_instruct
dtype: bfloat16 
data_parallelism: fsdp
fsdp_wrap_granularity: layer
fsdp_reshard_after_forward: true
tensor_parallel_size: 8
activation_checkpointing: true
torch_compile: false
optimizer_config:
    _type_: fairseq2.optim.factory.AdamWConfig
    lr: 1e-06
    betas:
    - 0.9
    - 0.95
    weight_decay: 0.1
    amsgrad: false
    maximize: false
    capturable: false
    differentiable: false
    impl: auto
    use_fp32: false
lr_scheduler: cosine-annealing
lr_scheduler_config:
    _type_: fairseq2.optim.lr_scheduler.factory.CosineAnnealingLRConfig
    cycle_len: null
    num_warmup_steps: 100
    cycle_mul: 1.0
    lr_mul: 1.0
    start_lr: 0.0
    final_lr: 1.0e-07
gradient_accumulation: 1
max_gradient_norm: null
fp16_loss_scale:
- 128.0
- 0.0001
max_num_steps: 50000
max_num_data_epochs: null
checkpoint_every_n_steps: 500
keep_last_n_checkpoints: 1
keep_last_n_models: 100
publish_metrics_every_n_steps: 10
seed: 2
profile: null
monitored_gang: false
anomaly_detection: false

ERROR1 ：fairseq2.recipes.config_manager.ConfigError: The size of the root gang (1) is not divisible by 'gang.tensor_parallel_size' (8). 
Please refer to file1 for details

ERROR2 :   after setting tensor_parallel_size: 1， raise error：fairseq2.assets.error.AssetError: The tokenizer of llama3_1_70b_instruct is  gated. Please visit https://ai.meta.com/llama/ to learn how to get access.

For error 2 , I have tried manually downloading the model using llamacli, but it gets downloaded to the root directory and ends up being deleted. I also attempted to download it from Hugging Face, but Fairseq2 could not recognize the local model path. When setting model: llama3_1_70b_instruct for automatic downloading, it prompts that I do not have permission. However, using huggingface-cli login and providing the appropriate access token did not resolve the issue.

Thank you very much for your help
[file1.pdf](https://github.com/user-attachments/files/18176997/file1.pdf)

**Comment by zyaoj** [comment]
The first error is similar to issue #855. Please check [the comment](https://github.com/facebookresearch/fairseq2/issues/855#issuecomment-2553411623).

For the second error message, you can check [the end to end fine-tuning tutorial](https://facebookresearch.github.io/fairseq2/nightly/tutorials/end_to_end_fine_tuning.html#model) for more instruction.

**Comment by cbalioglu** [comment]
@sunrise224 specifically check out this section: https://facebookresearch.github.io/fairseq2/nightly/tutorials/end_to_end_fine_tuning.html#multi-node

If you are on a single node with 8 GPUs, you can use torchrun:

```
torchrun --standalone --nproc-per-node 8 --no-python fairseq2 lm instruction_finetune ...
```

**Comment by cbalioglu** [comment]
Closing for now. Please let us know if you still have trouble after using `torchrun`.

**Comment by sunrise224** [comment]
Thank you for your help. I am now able to get the correct root gang size and have prepared the model.yaml.
 However, when I ran it again, an error occurred.
                             /Llama-3.1-70B-
                             Instruct/original/tokenizer.model' cannot be opened.                                  
                             third-party/sentencepiece/src/sentencepiece_processor.cc(1101)                        
                             [model_proto->ParseFromArray(serialized.data(), serialized.size())]
 I tried downloading the model using the Hugging Face CLI and also tried git lfs install & git clone model, but neither resolved the issue, and the same error persists.
